### ISSUE TITLE
Enforcing a package manager and committing a lockfile

### ISSUE THREAD

**Issue by madisonbullard** [daltn/rave-cafe-blog#2]
We should commit the lockfile to our repo, regardless of the package manager we choose. Longer read [here](https://www.arahansen.com/the-ultimate-guide-to-yarn-lock-lockfiles/#:~:text=Every%20project%20using%20yarn%20should,for%20installing%20the%20wrong%20packages.). The part that matters:

> **Should you commit yarn.lock?**
> Every project using yarn should commit the yarn lockfile to source control. The lockfile is the source of truth for telling other developers how to install dependencies for your project.
> 
> Without this lockfile, other developers will be at risk for installing the wrong packages. This could lead to any number of incompatibilities where there is a version mismatch and the project won't build or run. You don't want to be stuck saying "works on my machine!".

As far as package manager, I will advocate for using `pnpm` because, in my experience, it's fastest. But Yarn and NPM are great too if there's strong preference there.

@daltn @dereksaffe How yall feelin

**Comment by dereksaffe** [comment]
Good point on the lockfile. Haven’t used pnpm before so don’t have an
opinion necessarily on that - but if it’s functionally similar and has
better performance than npm I’m fine with it.

**Comment by daltn** [comment]
I'm game to commit the lock file and down to give pnpm a go since i'm generally using npm on my day to day and seems like a positive upgrade

**Comment by madisonbullard** [comment]
Too much friction lol. Closed the PR in favor of just using NPM! Glad to revisit down the line if we decide to make the change.
