### ISSUE TITLE
Moving repo to GitHub Organization ownership

### ISSUE THREAD

**Issue by madisonbullard** [daltn/rave-cafe-blog#7]
https://medium.com/@ajlehechka/why-you-should-create-a-github-organization-for-your-side-project-d7c941dbb45b

I'd love to use Projects as an option to track work :)

Want to create a Rave Cafe org and move ownership to that org @daltn ?

**Comment by daltn** [comment]
Funnily enough I had a rave cafe github org and deleted it cause of vercel only being able to use personal account repos for the free account. I've mainly been using netlify and am down to use netlify to host this site which allows for github org deployment. I'll spin one up.
